name: e2e

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:

env:
  DESTDIR: ./bin

jobs:
  registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          -
            image: "crazymax/buildx-pkg:latest"
            all: "true"
            loglevel: "debug"
          -
            image: "crazymax/buildx-pkg:latest"
            all: "true"
            wrap: "true"
            loglevel: "debug"
          -
            image: "crazymax/diun:4.20.1"
            all: "true"
            include: "/usr/local/bin"
            loglevel: "info"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: binary
      -
        name: Run
        run: |
          flags="--rm-dist"
          if [ -n "${{ matrix.loglevel }}" ]; then
            flags="${flags} --log-level ${{ matrix.loglevel }}"
          fi
          if [ "${{ matrix.all }}" = "true" ]; then
            flags="${flags} --all"
          fi
          if [ "${{ matrix.wrap }}" = "true" ]; then
            flags="${flags} --wrap"
          fi
          if [ -n "${{ matrix.include }}" ]; then
            flags="${flags} --include ${{ matrix.include }}"
          fi
          set -x
          ${{ env.DESTDIR }}/build/undock ${flags} ${{ matrix.image }} ./dist
      -
        name: Dist content
        run: |
          tree -nh ./dist

  docker-daemon:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: binary
      -
        name: Create Dockerfile
        run: |
          mkdir ./bin/test
          cat > ./bin/test/Dockerfile <<EOL
          FROM alpine
          RUN mkdir hello && echo "Hello, world!" > /hello/world
          EOL
      -
        name: Build image and load
        uses: docker/build-push-action@v3
        with:
          context: ./bin/test
          load: true
          tags: image:local
      -
        name: Run
        run: |
          ${{ env.DESTDIR }}/build/undock --rm-dist --include /hello docker-daemon://image:local ./dist
      -
        name: Dist content
        run: |
          tree -nh ./dist

  docker-archive:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        uses: docker/bake-action@v2
        with:
          targets: binary
      -
        name: Create docker archive
        run: |
          docker pull crazymax/buildx-pkg:latest
          docker save crazymax/buildx-pkg:latest > archive.tar
      -
        name: Run
        run: |
          ${{ env.DESTDIR }}/build/undock --rm-dist docker-archive://archive.tar ./dist
      -
        name: Dist content
        run: |
          tree -nh ./dist
